from decimal import Decimal

from unittest.mock import patch

from django.test import TestCase, override_settings
from rest_framework.test import APIClient

from core.models import User, Product, ProductVariant, Category
from sellers.models import SellerProfile
from shipping.models import ShippingAddress
from payments.models import PaymentGatewaySettings, Payment
from orders.models import Order, OrderItem, SubOrder
from .models import Combo, ComboItem

# Signals on Product/Variant save enqueue Celery tasks — run them inline so
# tests don't need a live broker.
TEST_SETTINGS = dict(
    CELERY_TASK_ALWAYS_EAGER=True,
    CELERY_TASK_EAGER_PROPAGATES=True,
)


def _make_seller(email, store=None):
    return User.objects.create_user(
        username=email, email=email, password='x', role='grower',
    )


def _make_variant(seller, name, price, stock):
    product = Product.objects.create(
        name=name, description='desc', seller=seller,
    )
    return ProductVariant.objects.create(
        product=product, name='Standard', base_price=price, price=price, stock=stock,
    )


@override_settings(**TEST_SETTINGS)
class ComboModelTests(TestCase):
    def setUp(self):
        self.s1 = _make_seller('s1@example.com')
        self.s2 = _make_seller('s2@example.com')
        self.v1 = _make_variant(self.s1, 'Glass Tank', Decimal('1000'), stock=5)
        self.v2 = _make_variant(self.s2, 'Carpet Plants', Decimal('500'), stock=2)

    def _combo(self, **kwargs):
        combo = Combo.objects.create(name='Aquascape Kit', **kwargs)
        ComboItem.objects.create(combo=combo, variant=self.v1, quantity=1)
        ComboItem.objects.create(combo=combo, variant=self.v2, quantity=2)
        return combo

    @property
    def expected_sum(self):
        # variant.price is recomputed from base_price + commission on save,
        # so derive the expectation from the live prices rather than hardcoding.
        return self.v1.price * 1 + self.v2.price * 2

    def test_original_price_sums_components(self):
        combo = self._combo()
        self.assertEqual(combo.original_price, self.expected_sum)

    def test_effective_price_defaults_to_sum(self):
        combo = self._combo()
        self.assertEqual(combo.effective_price, self.expected_sum)

    def test_price_override_wins(self):
        combo = self._combo(price=Decimal('1800'))
        self.assertEqual(combo.effective_price, Decimal('1800'))

    def test_total_price_adds_shipping(self):
        combo = self._combo(shipping_fee=Decimal('120'))
        self.assertEqual(combo.total_price, self.expected_sum + Decimal('120'))

    def test_seller_count_spans_multiple_sellers(self):
        combo = self._combo()
        self.assertEqual(combo.seller_count, 2)

    def test_in_stock_and_max_purchasable(self):
        combo = self._combo()
        # v2 has stock 2, needs 2/combo → only 1 combo buyable
        self.assertTrue(combo.in_stock)
        self.assertEqual(combo.max_purchasable, 1)

    def test_out_of_stock_when_component_insufficient(self):
        self.v2.stock = 1
        self.v2.save()
        combo = self._combo()
        self.assertFalse(combo.in_stock)
        self.assertEqual(combo.max_purchasable, 0)

    def test_slug_autogenerated_and_unique(self):
        c1 = Combo.objects.create(name='Same Name')
        c2 = Combo.objects.create(name='Same Name')
        self.assertNotEqual(c1.slug, c2.slug)


@override_settings(**TEST_SETTINGS)
class ComboApiTests(TestCase):
    def setUp(self):
        self.seller = _make_seller('seller@example.com')
        self.v1 = _make_variant(self.seller, 'Light', Decimal('300'), stock=10)

    def test_list_excludes_drafts_and_inactive(self):
        live = Combo.objects.create(name='Live Combo')
        ComboItem.objects.create(combo=live, variant=self.v1, quantity=1)
        Combo.objects.create(name='Draft Combo', is_draft=True)
        Combo.objects.create(name='Inactive Combo', is_active=False)

        resp = self.client.get('/api/combos/')
        self.assertEqual(resp.status_code, 200)
        names = [c['name'] for c in resp.json().get('results', resp.json())]
        self.assertIn('Live Combo', names)
        self.assertNotIn('Draft Combo', names)
        self.assertNotIn('Inactive Combo', names)

    def test_detail_by_slug(self):
        combo = Combo.objects.create(name='Detail Combo')
        ComboItem.objects.create(combo=combo, variant=self.v1, quantity=2)
        resp = self.client.get(f'/api/combos/{combo.slug}/')
        self.assertEqual(resp.status_code, 200)
        data = resp.json()
        self.assertEqual(data['name'], 'Detail Combo')
        self.assertEqual(len(data['items']), 1)
        self.assertEqual(data['items'][0]['quantity'], 2)


FAKE_RZP = {"id": "rzp_ord_COMBO", "amount": 100000, "currency": "INR"}


@override_settings(
    CELERY_TASK_ALWAYS_EAGER=True, CELERY_TASK_EAGER_PROPAGATES=True,
    EMAIL_BACKEND="django.core.mail.backends.locmem.EmailBackend", FCM_SERVER_KEY="test-key",
)
class ComboCheckoutTests(TestCase):
    """A combo checkout must expand into per-seller OrderItems, charge ONE flat
    combo shipping fee, tag each item with its combo, and decrement component
    stock on payment — reusing the existing SubOrder/stock machinery."""

    def _seller(self, email, store, slug):
        u = User.objects.create_user(username=email, email=email, password='x', role='grower')
        SellerProfile.objects.create(
            user=u, store_name=store, slug=slug,
            location_city='Kochi', location_state='Kerala', location_pincode='682001',
            pickup_address='1 Green St', shiprocket_pickup_location=store,
        )
        return u

    def _variant(self, seller, name, price, stock):
        cat = Category.objects.first() or Category.objects.create(name='Aquascaping', shipping_type='plant')
        p = Product.objects.create(name=name, seller=seller, is_active=True, is_draft=False)
        p.categories.add(cat)
        return ProductVariant.objects.create(
            product=p, name='Standard', base_price=price, price=price, stock=stock,
            weight=Decimal('0.5'), length=Decimal('10'), width=Decimal('10'), height=Decimal('10'),
            packed_weight_grams=500,
        )

    def setUp(self):
        self.client = APIClient()
        self.buyer = User.objects.create_user(username='b@t.com', email='b@t.com', password='x', role='collector')
        self.client.force_authenticate(user=self.buyer)
        self.address = ShippingAddress.objects.create(
            user=self.buyer, full_name='Buyer', phone='9876543210',
            address_line1='45 Lane', city='Mumbai', state='Maharashtra', pincode='400001',
        )
        PaymentGatewaySettings.objects.update_or_create(pk=1, defaults={'active_gateway': 'razorpay'})

        self.s1 = self._seller('s1@t.com', 'Glass Atelier', 'glass-atelier')
        self.s2 = self._seller('s2@t.com', 'Verdant Cove', 'verdant-cove')
        self.v1 = self._variant(self.s1, 'Glass tank', Decimal('4000'), stock=5)
        self.v2 = self._variant(self.s2, 'Anubias', Decimal('500'), stock=8)

        self.combo = Combo.objects.create(name='Starter Kit', shipping_fee=Decimal('360'))
        ComboItem.objects.create(combo=self.combo, variant=self.v1, quantity=1)
        ComboItem.objects.create(combo=self.combo, variant=self.v2, quantity=2)

    def _checkout(self, qty=1):
        with patch('orders.views.create_razorpay_order', return_value=FAKE_RZP), \
             patch('payments.tasks.schedule_payment_checks'):
            return self.client.post('/api/orders/checkout/', {
                'address_id': str(self.address.id),
                'combos': [{'combo_id': str(self.combo.id), 'quantity': qty}],
            }, format='json')

    def test_combo_checkout_expands_and_flat_ships(self):
        resp = self._checkout(qty=1)
        self.assertEqual(resp.status_code, 201, getattr(resp, 'data', None))
        order = Order.objects.get(user=self.buyer)

        # Two components → two OrderItems, one SubOrder per seller
        self.assertEqual(order.items.count(), 2)
        self.assertEqual(order.sub_orders.count(), 2)

        # Every item tagged with the combo
        for it in order.items.all():
            self.assertEqual(str(it.combo_id), str(self.combo.id))
            self.assertEqual(it.combo_name, 'Starter Kit')

        # ONE flat combo shipping fee — not a per-seller split
        self.assertEqual(order.shipping_fee, Decimal('360'))
        # Per-seller sub-orders carry no shipping (combo ships flat at master level)
        for sub in order.sub_orders.all():
            self.assertEqual(sub.shipping_fee, Decimal('0'))

        # Order detail serializer surfaces combo provenance so the UI can group
        from orders.serializers import OrderDetailSerializer
        data = OrderDetailSerializer(order).data
        self.assertTrue(all(str(i['combo_id']) == str(self.combo.id) for i in data['items']))
        self.assertTrue(all(i['combo_name'] == 'Starter Kit' for i in data['items']))

    @patch('orders.views.verify_razorpay_signature', return_value=True)
    def test_stock_decrements_on_payment(self, _mock_verify):
        v1_before, v2_before = self.v1.stock, self.v2.stock
        self._checkout(qty=2)
        payment = Payment.objects.latest('id')
        resp = self.client.post('/api/orders/checkout/verify/', {
            'gateway': 'razorpay',
            'razorpay_order_id': payment.razorpay_order_id,
            'razorpay_payment_id': 'pay_X',
            'razorpay_signature': 'sig',
        }, format='json')
        self.assertEqual(resp.status_code, 200, getattr(resp, 'data', None))

        self.v1.refresh_from_db(); self.v2.refresh_from_db()
        self.assertEqual(self.v1.stock, v1_before - 2)   # 1 per combo × qty 2
        self.assertEqual(self.v2.stock, v2_before - 4)   # 2 per combo × qty 2
