# Generated by Django 5.2.2 on 2026-05-09 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='razorpay_order_id',
            new_name='cashfree_order_id',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='razorpay_payment_id',
            new_name='cashfree_payment_id',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='razorpay_signature',
            new_name='cashfree_session_id',
        ),
    ]
