# Generated by Cursor on 2026-05-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_rename_razorpay_order_id_payment_cashfree_order_id_and_more"),
    ]

    operations = [
        # The _like index for the original razorpay_order_id was not renamed when
        # 0002_rename_... ran, so it must be dropped before we add razorpay_order_id back.
        migrations.RunSQL(
            sql="DROP INDEX IF EXISTS payments_payment_razorpay_order_id_f38fef72_like;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AddField(
            model_name="payment",
            name="gateway",
            field=models.CharField(
                choices=[("cashfree", "Cashfree"), ("razorpay", "Razorpay")],
                default="cashfree",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="cashfree_order_id",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="razorpay_order_id",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="razorpay_payment_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="razorpay_signature",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name="PaymentGatewaySettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "active_gateway",
                    models.CharField(
                        choices=[("cashfree", "Cashfree"), ("razorpay", "Razorpay")],
                        default="cashfree",
                        max_length=20,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]

