# Generated by Django 5.2.2 on 2026-05-14 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_add_payment_updated_at'),
        ('payments', '0004_add_payment_tracking_fields'),
    ]

    operations = [
    ]
