# Generated by Django 5.2.2 on 2026-05-17 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_merge_20260514_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='gateway',
            field=models.CharField(choices=[('cashfree', 'Cashfree'), ('razorpay', 'Razorpay')], default='cashfree', max_length=20),
        ),
    ]
