# Generated by Django 5.2.2 on 2026-04-23 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_featured',
            new_name='is_rare',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_trending',
        ),
        migrations.AddField(
            model_name='product',
            name='care_level',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Advanced', 'Advanced')], default='Easy', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='co2_requirement',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Low', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='growth_rate',
            field=models.CharField(choices=[('Slow', 'Slow'), ('Moderate', 'Moderate'), ('Fast', 'Fast')], default='Moderate', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='light_requirements',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='origin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='ph_range',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='scientific_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='water_temperature',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='height',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Height in cm', max_digits=10),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='length',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Length in cm', max_digits=10),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='weight',
            field=models.DecimalField(decimal_places=3, default=0.5, help_text='Weight in Kilograms', max_digits=10),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='width',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Width in cm', max_digits=10),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
