# Generated by Django 5.2.2 on 2026-04-24 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_is_featured_product_is_rare_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text="Seller's payout expectation", max_digits=12),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Platform commission percentage', max_digits=5),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='gst_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='GST percentage (e.g. 18.00)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Final price shown to buyers', max_digits=12),
        ),
    ]
