# Generated by Django 5.2.2 on 2026-04-25 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_productvariant_base_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tagline',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
