# Generated by Django 5.2.2 on 2026-04-27 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_user_avatar_url_user_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='shipping_type',
            field=models.CharField(choices=[('plant', 'Plant / Live Specimen'), ('accessory', 'Accessory / Tool'), ('heavy', 'Heavy Item (>3kg)'), ('flat', 'Flat Rate Item')], default='plant', max_length=20),
        ),
    ]
