# Generated by Django 5.2.2 on 2026-05-06 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_add_wishlist_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='item_category',
            field=models.CharField(choices=[('light', 'Light Item'), ('heavy', 'Heavy Item')], default='light', help_text='Light: plants/moss/isopods. Heavy: rocks/substrate/hardscape.', max_length=10),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='packed_weight_grams',
            field=models.PositiveIntegerField(blank=True, help_text='Actual weight when packed for shipping (grams, 1–30000)', null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='height',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Box height in cm', max_digits=10),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='length',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Box length in cm', max_digits=10),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='width',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Box breadth in cm', max_digits=10),
        ),
    ]
