# Generated by Django 5.2.2 on 2026-05-08 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_add_shipping_weight_fields_to_productvariant'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='commission_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Leave blank to inherit from parent category', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='gst_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Leave blank to inherit from parent category', max_digits=5, null=True),
        ),
        migrations.CreateModel(
            name='CategoryShippingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_weight_grams', models.PositiveIntegerField(default=0, help_text='Lower bound (inclusive) in grams')),
                ('max_weight_grams', models.PositiveIntegerField(blank=True, help_text="Upper bound (exclusive) in grams; leave blank for 'above max'", null=True)),
                ('rate', models.DecimalField(decimal_places=2, help_text='Shipping fee in INR for this weight tier', max_digits=8)),
                ('free_above_order_value', models.DecimalField(blank=True, decimal_places=2, help_text='Order subtotal (INR) above which shipping is free; leave blank to disable', max_digits=10, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipping_rates', to='core.category')),
                ('sub_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipping_rates', to='core.subcategory')),
            ],
            options={
                'verbose_name': 'Category Shipping Rate',
                'verbose_name_plural': 'Category Shipping Rates',
                'ordering': ['min_weight_grams'],
            },
        ),
    ]
