# Generated by Django 5.2.2 on 2026-05-10 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_productreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image of the plant/product', null=True, upload_to='reviews/'),
        ),
    ]
