# Generated by Django 5.2.2 on 2026-05-16 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_productreview_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='variant_type',
            field=models.CharField(choices=[('Plant', 'Plant'), ('Rhizome', 'Rhizome'), ('Pot', 'Pot'), ('Clump', 'Clump'), ('Tissue Culture', 'Tissue Culture'), ('Cutting', 'Cutting'), ('Bunch', 'Bunch'), ('Mat', 'Mat'), ('Cup', 'Cup'), ('Emersed', 'Emersed'), ('Submerged', 'Submerged'), ('Seedling', 'Seedling'), ('Bulb', 'Bulb'), ('Corm', 'Corm'), ('Dry Start', 'Dry Start'), ('Colony', 'Colony'), ('Pair', 'Pair'), ('Trio', 'Trio'), ('Other', 'Other')], default='Plant', help_text='What form is this variant? e.g. Rhizome, Clump, Tissue Culture', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='care_level',
            field=models.CharField(default='Easy', help_text='Single value (Easy) or range (Easy to Advanced)', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='growth_rate',
            field=models.CharField(default='Moderate', help_text='Single value (Slow) or range (Slow to Fast)', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='light_requirements',
            field=models.CharField(default='Medium', help_text='Single value (Low) or range (Low to High)', max_length=50),
        ),
    ]
