# Generated by Django 5.2.2 on 2026-05-16 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_variant_type_botanical_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_draft',
            field=models.BooleanField(db_index=True, default=False, help_text='True = saved as draft (not visible to buyers). False = published or archived.'),
        ),
    ]
