# Generated by Django 5.2.2 on 2026-05-24 12:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_increase_product_slug_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BugReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contact_info', models.CharField(blank=True, help_text='Email or Phone for guest users', max_length=255, null=True)),
                ('description', models.TextField()),
                ('images', models.JSONField(blank=True, default=list, help_text='List of Firebase image URLs')),
                ('status', models.CharField(choices=[('unresolved', 'Unresolved'), ('resolved', 'Resolved')], default='unresolved', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bug_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
