# Generated by Django 5.2.2 on 2026-05-24 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_bugreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='item_category',
            field=models.CharField(choices=[('light', 'Light Item'), ('heavy', 'Heavy Item'), ('hybrid', 'Hybrid (Light + Heavy)')], default='light', help_text='Light: plants/moss/isopods. Heavy: rocks/substrate/hardscape. Hybrid: mixed items.', max_length=10),
        ),
    ]
