# Generated by Django 5.2.2 on 2026-05-25 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_productvariant_item_category'),
        ('core', '0019_remove_product_sub_category_product_sub_categories'),
    ]

    operations = [
    ]
