# Generated by Django 5.2.2 on 2026-05-30 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_merge_20260525_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='buyer_commission_rate',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Deduction % from seller payout (toggle OFF) or part of total deduction from listed price (toggle ON).', max_digits=5),
        ),
        migrations.AddField(
            model_name='user',
            name='price_is_buyer_final',
            field=models.BooleanField(default=False, help_text="OFF: listed price is the seller's reference; buyer pays L*(1+seller_rate). ON: listed price IS what buyer pays; seller payout = L*(1-(seller_rate+buyer_rate))."),
        ),
        migrations.AddField(
            model_name='user',
            name='seller_commission_rate',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text="Markup % added on top of seller's listed price (toggle OFF) or part of total deduction from listed price (toggle ON).", max_digits=5),
        ),
    ]
