# Generated by Django 5.2.2 on 2026-06-13 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_user_buyer_commission_rate_user_price_is_buyer_final_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryComplement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.PositiveSmallIntegerField(default=0, help_text='Lower number = shown first when multiple rules match.')),
                ('source_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complement_rules', to='core.category')),
                ('target_categories', models.ManyToManyField(help_text='Products from these categories appear as complementary recommendations.', related_name='complemented_by', to='core.category')),
            ],
            options={
                'verbose_name': 'Category Complement Rule',
                'verbose_name_plural': 'Category Complement Rules',
                'ordering': ['priority'],
            },
        ),
    ]
