# Generated by Django 5.2.2 on 2026-09-08 06:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockSyncSession',
            fields=[
                ('key', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=32)),
                ('seller_email', models.EmailField(blank=True, default='', max_length=254)),
                ('price_changes', models.JSONField(blank=True, default=dict)),
                ('new_products', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
