# Generated by Django 5.2.2 on 2026-09-18 13:44

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0021_user_buyer_commission_rate_user_price_is_buyer_final_and_more'),
        ('orders', '0014_sellersettlement_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='Buyers type this at checkout. Stored upper-case.', max_length=40, unique=True)),
                ('name', models.CharField(help_text="Short label shown to the buyer, e.g. '10% off aquatic plants'", max_length=120)),
                ('description', models.TextField(blank=True)),
                ('discount_type', models.CharField(choices=[('percent', 'Percentage off'), ('fixed', 'Fixed amount off')], default='percent', max_length=10)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Percent (e.g. 10 = 10%) or fixed ₹ amount, per discount_type', max_digits=10)),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Cap on the ₹ discount. Leave blank for no cap.', max_digits=10, null=True)),
                ('funded_by', models.CharField(choices=[('platform', 'Platform'), ('seller', 'Seller')], default='platform', help_text="Who absorbs the discount. 'Seller' reduces the seller's payout.", max_length=10)),
                ('min_cart_value', models.DecimalField(decimal_places=2, default=0, help_text='Minimum whole-cart subtotal (₹) before the coupon applies.', max_digits=12)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_until', models.DateTimeField(blank=True, help_text='Blank = never expires', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('usage_limit_total', models.PositiveIntegerField(blank=True, help_text='Blank = unlimited', null=True)),
                ('usage_limit_per_user', models.PositiveIntegerField(blank=True, help_text='Blank = unlimited', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(blank=True, help_text='Only products in these categories qualify. Blank = any category.', related_name='coupons', to='core.category')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_coupons', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(blank=True, help_text="Only this seller's products qualify. Blank = any seller.", limit_choices_to={'is_verified_seller': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CouponRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='coupons.coupon')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_redemption', to='orders.order')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupon_redemptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
