# Generated by Django 5.2.2 on 2026-06-17 05:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0022_category_complement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('tagline', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('image_url', models.URLField(blank=True, help_text='Hero image for the combo card and detail page.', max_length=1000, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Optional fixed combo price (₹). Leave blank to price at the live sum of all component variant prices.', max_digits=12, null=True)),
                ('shipping_fee', models.DecimalField(decimal_places=2, default=0, help_text='Fixed shipping charge for the whole combo (₹). Charged once per combo, not split per seller.', max_digits=10)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_draft', models.BooleanField(db_index=True, default=False, help_text='True = hidden from buyers (work in progress).')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_combos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComboImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=1000)),
                ('is_primary', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('combo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='combos.combo')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ComboItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('combo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='combos.combo')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combo_items', to='core.productvariant')),
            ],
            options={
                'ordering': ['sort_order'],
                'unique_together': {('combo', 'variant')},
            },
        ),
    ]
