# Generated by Django 5.2.2 on 2026-06-28 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='combo',
            name='combo_type',
            field=models.CharField(choices=[('complete_build', 'Complete build'), ('plants_only', 'Plants only'), ('hardscape', 'Hardscape'), ('fertilizers', 'Fertilizers'), ('other', 'Other')], db_index=True, default='other', help_text='Drives the storefront type-filter chips.', max_length=20),
        ),
        migrations.AddField(
            model_name='combo',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False, help_text="Show in the home page 'Featured Combos' rail."),
        ),
    ]
