# Generated by Django 5.2.2 on 2026-04-23 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='brand_color',
            field=models.CharField(default='#0A3029', max_length=7),
        ),
    ]
