# Generated by Django 5.2.2 on 2026-04-26 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0002_sellerprofile_brand_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='experience_years',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='expertise_tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='identity_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='infrastructure_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
