# Generated by Django 5.2.2 on 2026-05-05 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0004_allowedseller_sellerprofile_is_featured_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='location_state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='pickup_address',
            field=models.CharField(blank=True, help_text='Street address for NimbusPost pickup', max_length=255, null=True),
        ),
    ]
