# Generated by Django 5.2.2 on 2026-05-06 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0005_nimbuspost_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='icon_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
