# Generated by Django 5.2.2 on 2026-05-17 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0006_add_icon_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='payout_account',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='payout_type',
            field=models.CharField(blank=True, choices=[('upi', 'UPI'), ('bank', 'Bank Account')], default='upi', max_length=10),
        ),
    ]
