# Generated by Django 5.2.2 on 2026-05-17 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0007_add_payout_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='account_holder_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='payout_account',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
