# Generated by Django 5.2.2 on 2026-05-22 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0012_seller_profile_shiprocket_pickup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerprofile',
            name='pickup_address',
            field=models.CharField(blank=True, help_text='Street address for pickup', max_length=255, null=True),
        ),
    ]
