# Generated by Django 5.2.2 on 2026-05-24 14:58

import sellers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0015_default_shipping_days'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='sellerblackoutdate',
            new_name='sellers_sel_seller__0c3a1b_idx',
            old_name='sellers_sel_seller__7b9f4d_idx',
        ),
        migrations.AlterField(
            model_name='sellerblackoutdate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='shipping_days',
            field=models.JSONField(blank=True, default=sellers.models._default_shipping_days, help_text='Weekdays the seller ships: 0=Mon, 1=Tue, 2=Wed, 3=Thu, 4=Fri, 5=Sat, 6=Sun. Defaults to Mon/Wed/Fri.'),
        ),
        migrations.AlterField(
            model_name='sellershippingconfig',
            name='item_category',
            field=models.CharField(choices=[('light', 'Light'), ('heavy', 'Heavy'), ('hybrid', 'Hybrid (Light + Heavy)')], max_length=10),
        ),
        migrations.AlterField(
            model_name='shippingdefaultconfig',
            name='item_category',
            field=models.CharField(choices=[('light', 'Light'), ('heavy', 'Heavy'), ('hybrid', 'Hybrid (Light + Heavy)')], max_length=10, unique=True),
        ),
    ]
