# Generated by Django 5.2.2 on 2026-05-20 15:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.CharField(max_length=15)),
                ('about_aquarium', models.TextField()),
                ('image_urls', models.JSONField(blank=True, default=list)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_winner', models.BooleanField(default=False)),
                ('is_disqualified', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Competition Entry',
                'verbose_name_plural': 'Competition Entries',
                'ordering': ['submitted_at'],
            },
        ),
    ]
