# Generated by Django 5.2.2 on 2026-05-31 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionentry',
            name='follows_instagram',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='competitionentry',
            name='instagram_handle',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
