# Generated by Django 5.2.2 on 2026-06-08 09:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0002_competitionentry_follows_instagram_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionentry',
            name='prize_tier',
            field=models.CharField(blank=True, choices=[('', '—'), ('first', '1st Place'), ('second', '2nd Place'), ('third', '3rd Place'), ('consolation', '4th — Consolation'), ('mystery', 'Mystery Box')], default='', help_text='Set to assign a prize. Only one entry per tier; saving here also flips is_winner.', max_length=20),
        ),
        migrations.CreateModel(
            name='EntryVote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='competition.competitionentry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['entry'], name='competition_entry_i_f9664b_idx')],
                'unique_together': {('entry', 'user')},
            },
        ),
    ]
