# Generated by Django 5.2.2 on 2026-04-25 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('nimbuspost_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('awb_number', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('label_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('pickup_scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipment', to='orders.order')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
