# Generated by Django 5.2.2 on 2026-05-06 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0003_shipment_seller_alter_shipment_order_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shippingaddress',
            options={'ordering': ['-is_default', '-created_at']},
        ),
    ]
