# Generated by Django 5.2.2 on 2026-05-05 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0003_shipment_seller_alter_shipment_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='courier_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='manifest_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='nimbuspost_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
