# Generated by Django 5.2.2 on 2026-05-06 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0004_nimbuspost_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='package_image_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
