# Generated by Django 5.2.2 on 2026-05-08 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0004_alter_shippingaddress_options'),
        ('shipping', '0005_package_image_url'),
    ]

    operations = [
    ]
