# Generated by Django 5.2.2 on 2026-05-15 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0006_merge_20260508_1032'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogisticsProviderSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_provider', models.CharField(choices=[('nimbuspost', 'NimbusPost'), ('shiprocket', 'Shiprocket')], default='nimbuspost', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Logistics Provider Settings',
                'verbose_name_plural': 'Logistics Provider Settings',
            },
        ),
    ]
