# Generated by Django 5.2.2 on 2026-05-06 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_add_suborder_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='suborder',
            name='actual_breadth_cm',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suborder',
            name='actual_height_cm',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suborder',
            name='actual_length_cm',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suborder',
            name='actual_weight_grams',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
