# Generated by Cursor on 2026-05-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_order_payment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_gateway",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]

