# Generated by Django 5.2.2 on 2026-05-10 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_payment_gateway'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suborder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('placed', 'Placed'), ('confirmed', 'Confirmed'), ('packing', 'Packing'), ('shipped', 'Shipped'), ('in_transit', 'In Transit'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('delivery_failed', 'Delivery Failed'), ('doa_raised', 'DOA Complaint Raised'), ('cancelled', 'Cancelled')], default='pending', max_length=30),
        ),
    ]
