# Generated by Django 5.2.2 on 2026-05-14 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_add_payment_status_to_order'),
        ('orders', '0006_alter_suborder_status'),
    ]

    operations = [
    ]
