# Generated by Django 5.2.2 on 2026-07-05 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_sellersettlement_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='combo_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='combo_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
