# Generated by Django 5.2.2 on 2026-09-22 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_order_coupon_order_coupon_code_order_discount_amount_and_more'),
        ('orders', '0015_orderitem_combo_id_orderitem_combo_name'),
    ]

    operations = [
    ]
